drop policy "Enable users to manage their own todos only" on "public"."todos";

revoke delete on table "public"."todos" from "anon";

revoke insert on table "public"."todos" from "anon";

revoke references on table "public"."todos" from "anon";

revoke select on table "public"."todos" from "anon";

revoke trigger on table "public"."todos" from "anon";

revoke truncate on table "public"."todos" from "anon";

revoke update on table "public"."todos" from "anon";

revoke delete on table "public"."todos" from "authenticated";

revoke insert on table "public"."todos" from "authenticated";

revoke references on table "public"."todos" from "authenticated";

revoke select on table "public"."todos" from "authenticated";

revoke trigger on table "public"."todos" from "authenticated";

revoke truncate on table "public"."todos" from "authenticated";

revoke update on table "public"."todos" from "authenticated";

revoke delete on table "public"."todos" from "service_role";

revoke insert on table "public"."todos" from "service_role";

revoke references on table "public"."todos" from "service_role";

revoke select on table "public"."todos" from "service_role";

revoke trigger on table "public"."todos" from "service_role";

revoke truncate on table "public"."todos" from "service_role";

revoke update on table "public"."todos" from "service_role";

alter table "public"."todos" drop constraint "todos_parent_task_fkey";

alter table "public"."todos" drop constraint "todos_user_fkey";

alter table "public"."todos" drop constraint "todos_pkey";

drop index if exists "public"."todos_pkey";

drop table "public"."todos";


  create table "public"."tasks" (
    "id" bigint generated by default as identity not null,
    "user" uuid,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying,
    "content" text,
    "status" smallint,
    "priority" smallint,
    "effort" smallint,
    "due_date" date,
    "parent_task" bigint
      );


alter table "public"."tasks" enable row level security;

CREATE UNIQUE INDEX todos_pkey ON public.tasks USING btree (id);

alter table "public"."tasks" add constraint "todos_pkey" PRIMARY KEY using index "todos_pkey";

alter table "public"."tasks" add constraint "todos_parent_task_fkey" FOREIGN KEY (parent_task) REFERENCES public.tasks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "todos_parent_task_fkey";

alter table "public"."tasks" add constraint "todos_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "todos_user_fkey";

grant delete on table "public"."tasks" to "anon";

grant insert on table "public"."tasks" to "anon";

grant references on table "public"."tasks" to "anon";

grant select on table "public"."tasks" to "anon";

grant trigger on table "public"."tasks" to "anon";

grant truncate on table "public"."tasks" to "anon";

grant update on table "public"."tasks" to "anon";

grant delete on table "public"."tasks" to "authenticated";

grant insert on table "public"."tasks" to "authenticated";

grant references on table "public"."tasks" to "authenticated";

grant select on table "public"."tasks" to "authenticated";

grant trigger on table "public"."tasks" to "authenticated";

grant truncate on table "public"."tasks" to "authenticated";

grant update on table "public"."tasks" to "authenticated";

grant delete on table "public"."tasks" to "service_role";

grant insert on table "public"."tasks" to "service_role";

grant references on table "public"."tasks" to "service_role";

grant select on table "public"."tasks" to "service_role";

grant trigger on table "public"."tasks" to "service_role";

grant truncate on table "public"."tasks" to "service_role";

grant update on table "public"."tasks" to "service_role";


  create policy "Enable users to manage their own todos only"
  on "public"."tasks"
  as permissive
  for all
  to authenticated
using ((( SELECT auth.uid() AS uid) = "user"));



